# Generated by Django 5.2 on 2025-04-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='Слово')),
                ('image', models.ImageField(upload_to='cards/images/', verbose_name='Иллюстрация')),
                ('translation', models.CharField(max_length=100, verbose_name='Перевод')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
